# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdee3a8ecf759e66f2e056092074ab947ba4ae61efedf02e9b0d4dab507c9cae3a73dd2949a864fcc38eec543f865015092d6550b38c7ec2b08493d4f6a125c0

test:
  secret_key_base: 58ce259947f4b7b593b2a1f4e7e74a399cf9fe3ce27d032dfdaf95f90adba02528a4d010f504046ce2d7005720bbaaac4d306543572298388bf0251d043f0bd0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
